site_name: Codexmetry
site_url: https://jhjang101.github.io/codexmetry/

# 1. Pathing Configuration
docs_dir: docs    # Where you write your Markdown
site_dir: site/documentation # Where MkDocs outputs the HTML

# 2. Theme & Branding
theme:
  name: material
  logo: assets/logo_default.svg
  favicon: assets/favicon.svg
  palette: 
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

# 3. Content Navigation Structure
nav:
  - Overview: index.md
  - How-To Guides:
    - Deployment: guides/deployment.md
    # - Workflow: guides/workflow.md
    # - Maintenance: guides/maintenance.md
    - Restoration: guides/restore.md
  - Technical Reference:
    - Orders (CDX): reference/orders.md
    - Invoices: reference/invoices.md

# 4. Plugins
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences

# Versioning Configuration
extra:
  version:
    provider: mike