"""Add quote signature toggle and audit label

Revision ID: 01e0b5586231
Revises: 63f5b3df7e41
Create Date: 2026-04-30 14:29:34.536324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e0b5586231'
down_revision = '63f5b3df7e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_quote_signature', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('show_quote_signature')

    # ### end Alembic commands ###
