"""add order_id to audit logs for deal timeline

Revision ID: 06aa3d3825bb
Revises: 681053fa74b5
Create Date: 2026-04-04 21:53:22.069067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aa3d3825bb'
down_revision = '681053fa74b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
