"""add version_counter for persistent pdf versioning

Revision ID: 12706d882433
Revises: 21a3a88771d4
Create Date: 2026-04-26 12:54:30.877529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12706d882433'
down_revision = '21a3a88771d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_counter', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_counter', sa.Integer(), server_default='1', nullable=False))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_counter', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('version_counter')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('version_counter')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('version_counter')

    # ### end Alembic commands ###
