"""schema update

Revision ID: 17aaf8a38ab1
Revises: ef0b61833297
Create Date: 2026-03-09 10:17:33.251891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aaf8a38ab1'
down_revision = 'ef0b61833297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ship_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key('fk_invoices_carrier_id', 'carriers', ['carrier_id'], ['id'])

    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_contacts', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('company_email')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ship_date')
        batch_op.drop_column('carrier_id')

    op.drop_table('carriers')
    # ### end Alembic commands ###
