"""enforce unique constraints and indexes on document numbers

Revision ID: 199ca62d3358
Revises: 12706d882433
Create Date: 2026-04-26 17:07:45.407818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199ca62d3358'
down_revision = '12706d882433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjustments_adjustment_number'), ['adjustment_number'], unique=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_expense_number'), ['expense_number'], unique=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_orders_order_number'), type_='unique')
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_payment_number'), ['payment_number'], unique=True)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_quote_number'), ['quote_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_quote_number'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_number'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.create_unique_constraint(batch_op.f('uq_orders_order_number'), ['order_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_number'))

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjustments_adjustment_number'))

    # ### end Alembic commands ###
