"""Add multi-address snapshots

Revision ID: 1ddf2cd153fe
Revises: 58f90764441d
Create Date: 2026-05-28 18:16:52.827621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddf2cd153fe'
down_revision = '58f90764441d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('address', new_column_name='primary_address')
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_from_address', sa.Text(), nullable=True))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.Text(), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('quote_address')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('paid_from_address')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('primary_address', new_column_name='address')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
