"""rename terms_snapshot to terms

Revision ID: 21a3a88771d4
Revises: e7016677c915
Create Date: 2026-04-26 11:11:51.410939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a3a88771d4'
down_revision = 'e7016677c915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms', sa.Text(), nullable=True))
        batch_op.drop_column('terms_snapshot')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms', sa.Text(), nullable=True))
        batch_op.drop_column('terms_snapshot')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms', sa.Text(), nullable=True))
        batch_op.drop_column('terms_snapshot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('terms')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('terms')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('terms')

    # ### end Alembic commands ###
