"""standardize boolean defaults

Revision ID: 21eec8504ace
Revises: c9941dbbf7d4
Create Date: 2026-04-02 10:12:58.463597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eec8504ace'
down_revision = 'c9941dbbf7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_invoice_items_po_item_id_po_items'), 'po_items', ['po_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoice_items_po_item_id_po_items'), type_='foreignkey')

    # ### end Alembic commands ###
