"""add system and order links to adjustments

Revision ID: 53b237a60ad5
Revises: 21eec8504ace
Create Date: 2026-04-02 16:11:38.376800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b237a60ad5'
down_revision = '21eec8504ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_adjustments_order_id_orders'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_adjustments_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_adjustments_invoice_id_invoices'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_adjustments_order_id_orders'), type_='foreignkey')
        batch_op.drop_column('is_system')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
