"""Add bank account name to metadata

Revision ID: 58f90764441d
Revises: 3f5374990138
Create Date: 2026-05-27 11:45:16.759380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f90764441d'
down_revision = '3f5374990138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')

    # ### end Alembic commands ###
