"""add client and po links to adjustments

Revision ID: 681053fa74b5
Revises: 9b627734c98a
Create Date: 2026-04-04 15:46:34.008760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681053fa74b5'
down_revision = '9b627734c98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('po_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_adjustments_po_id_purchase_orders'), 'purchase_orders', ['po_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_adjustments_client_id_clients'), 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_adjustments_client_id_clients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_adjustments_po_id_purchase_orders'), type_='foreignkey')
        batch_op.drop_column('po_id')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
