"""add target_label in AuditLog

Revision ID: 92053ec64941
Revises: 17aaf8a38ab1
Create Date: 2026-03-15 16:29:15.912958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92053ec64941'
down_revision = '17aaf8a38ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_label', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('target_label')

    # ### end Alembic commands ###
