"""add is_system to adjustment categories

Revision ID: 9b627734c98a
Revises: 53b237a60ad5
Create Date: 2026-04-02 21:04:49.668616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b627734c98a'
down_revision = '53b237a60ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustment_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustment_categories', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    # ### end Alembic commands ###
