"""Add maintenance mode flag

Revision ID: a75b4bae39d1
Revises: b289c327a516
Create Date: 2026-04-29 20:31:01.510117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75b4bae39d1'
down_revision = 'b289c327a516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_maintenance_mode', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('is_maintenance_mode')

    # ### end Alembic commands ###
