"""Hardening unique constraints and identity attribute

Revision ID: b289c327a516
Revises: bf2e5ef1619e
Create Date: 2026-04-29 11:48:29.906897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b289c327a516'
down_revision = 'bf2e5ef1619e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_carriers_type'), ['type'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clients_company_name'), ['company_name'])

    with op.batch_alter_table('payment_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payment_types_type'), ['type'])

    with op.batch_alter_table('po_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_po_types_type'), ['type'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vendors_company_name'), ['company_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendors_company_name'), type_='unique')

    with op.batch_alter_table('po_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_po_types_type'), type_='unique')

    with op.batch_alter_table('payment_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_types_type'), type_='unique')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clients_company_name'), type_='unique')

    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_carriers_type'), type_='unique')

    # ### end Alembic commands ###
