"""add parent_id and self-referential relationships to audit_logs

Revision ID: e10c952d1345
Revises: 06aa3d3825bb
Create Date: 2026-04-07 21:28:41.855086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10c952d1345'
down_revision = '06aa3d3825bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_parent_id_audit_logs'), 'audit_logs', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_parent_id_audit_logs'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
