"""add terms_snapshot columns

Revision ID: e7016677c915
Revises: a156e9220171
Create Date: 2026-04-19 18:02:53.794229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7016677c915'
down_revision = 'a156e9220171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.Text(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.Text(), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('terms_snapshot')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('terms_snapshot')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('terms_snapshot')

    # ### end Alembic commands ###
