"""schema update

Revision ID: ef0b61833297
Revises: ffa5acdc6edb
Create Date: 2026-03-07 12:57:27.613525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0b61833297'
down_revision = 'ffa5acdc6edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_revenue', sa.Boolean(), server_default='1', nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_placement', sa.String(length=20), server_default='lineitem', nullable=False))
        batch_op.drop_column('financial_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=51),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=51),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_type', sa.VARCHAR(length=20), server_default=sa.text("'revenue'"), nullable=False))
        batch_op.drop_column('document_placement')

    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_column('is_revenue')

    # ### end Alembic commands ###
