"""re-initialize migrations

Revision ID: fbb2ad16fb49
Revises: 
Create Date: 2026-03-06 15:56:56.712622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb2ad16fb49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cogs', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_type', sa.String(length=20), server_default='revenue', nullable=False))

    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_fax', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payable_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_swift', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_routing', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('default_net_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('default_quote_expiry_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('default_quote_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_invoice_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_po_terms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('default_po_terms')
        batch_op.drop_column('default_invoice_terms')
        batch_op.drop_column('default_quote_terms')
        batch_op.drop_column('default_quote_expiry_days')
        batch_op.drop_column('default_net_days')
        batch_op.drop_column('bank_account')
        batch_op.drop_column('bank_routing')
        batch_op.drop_column('bank_swift')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('payable_address')
        batch_op.drop_column('company_fax')
        batch_op.drop_column('company_phone')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('financial_type')

    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_column('is_cogs')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
