"""add phase 8 columns with server defaults

Revision ID: ffa5acdc6edb
Revises: fbb2ad16fb49
Create Date: 2026-03-06 16:06:42.564786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa5acdc6edb'
down_revision = 'fbb2ad16fb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_net_days', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('default_quote_expiry_days', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('default_quote_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_invoice_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_po_terms', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=51),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=51),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('settings_metadata', schema=None) as batch_op:
        batch_op.drop_column('default_po_terms')
        batch_op.drop_column('default_invoice_terms')
        batch_op.drop_column('default_quote_terms')
        batch_op.drop_column('default_quote_expiry_days')
        batch_op.drop_column('default_net_days')

    # ### end Alembic commands ###
